name: Docker Container with GitHub Actions
on: push

jobs:
  node-docker:
    container:
      image: node:17-alpine3.14
    runs-on: ubuntu-latest
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release