name: ENV Variables
on: push
env:
  WF_ENV: Available to all jobs
  GH_ENV: ${{ secrets.GIT_HUB_ENV_VAR }}

jobs:
  log-env-1:
    env:
      JOB_ENV: Available to all steps
    runs-on: ubuntu-latest
    steps:
      - name: log-env-1-step1
        env:
          STEP_ENV: Available to only log-env-1-step1
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
      - name: log-env-1-step2
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"

  log-env-2:
    runs-on: ubuntu-latest
    steps:
      - name: log-env-2-step1
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
  
  log-default-env: 
    runs-on: ubuntu-latest
    steps:
      - name: Default ENV Variables 
        run: |
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
  
  log-github-secrets: 
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Secrets as ENV Variables  
        run: |
          echo "GitHub Secret Env Variable: ${GH_ENV}"