name: Matrix and Strategy

on: pull_request

jobs:
  matrix-strategy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node_version: [8,10]
        exclude:
          - os: ubuntu-latest
            node_version: 8
        include:
          - os: ubuntu-latest
            node_version: 10
            is_ubuntu_10: "true"
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env: 
      IS_UBUNTU_10: ${{ matrix.is_ubuntu_10 }}
    steps:
      - name: log os
        run: echo ${{ matrix.os }}
      - name: log node version
        run: node -v
      - name: changing node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: After setup node log node version
        run: node -v
      - name: Only for ubuntu-latest and node-version 10
        run: echo $IS_UBUNTU_10
