name: simple-workflow-for-shell-commands

on:
  push:
  schedule:
    - cron: '0/5 * * * *'
    - cron: '0/6 * * * *'
  repository_dispatch:
    types:
      - external-build-test
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - assigned
      - synchronize

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          npm -v
          node -v
      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Before Checkout
        run: |
          pwd
          ls
        shell: bash
      - name: Checkout Action
        id: check-action-step
        uses: actions/checkout@v2
      - name: After Checkout
        run: |
          pwd
          ls
        shell: bash
      - name: Directory Powershell
        run: Get-Location
      - name: some defined objects
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          echo "${{ steps.check-action-step.outputs.time }}"
        shell: bash
      - name: client payload repository_dispatch
        run: echo "${{ github.event.client_payload.env }}"
        shell: bash